
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 24 12:30:37 BRST 2017
//----------------------------------------------------

package analisadorSintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BGN = 4;
  public static final int ADDOP = 20;
  public static final int READ = 15;
  public static final int RELOP = 19;
  public static final int ELSE = 9;
  public static final int identifier = 26;
  public static final int THEN = 16;
  public static final int WHILE = 11;
  public static final int END = 5;
  public static final int ABREPARENTESE = 21;
  public static final int IF = 17;
  public static final int LITERAL = 13;
  public static final int F_CHAVE = 25;
  public static final int MULOP = 23;
  public static final int WRITE = 18;
  public static final int DO = 10;
  public static final int ATRIBUICAO = 12;
  public static final int EOF = 0;
  public static final int VIRG = 7;
  public static final int DIGITO = 14;
  public static final int PRG = 2;
  public static final int A_CHAVE = 24;
  public static final int error = 1;
  public static final int DCL = 3;
  public static final int FECHAPARENTESE = 22;
  public static final int INTEGER = 8;
  public static final int P_VIRG = 6;
}

