
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 08 23:34:59 BRST 2017
//----------------------------------------------------

package analisadorlexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTEGER = 8;
  public static final int DCL = 3;
  public static final int P_VIRG = 6;
  public static final int BGN = 4;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int IDENTIFIER = 9;
  public static final int PRG = 2;
  public static final int VIRG = 7;
  public static final int END = 5;
}

